codu-code/codu

- CONTRIBUTING.md
- README.md
Adds a simple contribution guide based on some of the projects over at [EddieHub](https://github.com/EddieHubCommunity).
Based on issue closes #4.
> Adds CONTRIBUTING.md and link from README

- components/Nav/Nav.tsx
> fixed zIndex issue on popover with z-10

- pages/index.tsx
> fixed padding in Benefits section for mobile

- components/Footer/Footer.tsx
- components/Nav/Nav.tsx
- config/site_settings.ts
- pages/index.tsx
- Adds link to the Meetup
- Adds alt tags to the cloud images
- Dynamically creates <Link> or external <a> depending on URL. 
- Fix some spacing issues on the homepage
> Adds link from events to redirect to Meetup

- components/Nav/Nav.tsx
I forgot to add the changes to the mobile nav 🤦🏻‍♂️
- Changes to <Link> or <a> depending on URL.
> Adds link changes to mobile nav

- components/BioBar/BioBar.tsx
- config/site_settings.ts
- content/articles/example.md
- content/articles/five-npm-tips-and-tricks.md
- lib/blog.ts
- next.config.js
- pages/articles/[slug].tsx
Add a bio bar for authors at end of articles
- Uses a userId to fetch the author data.
Add article "5 NPM TIPS/TRICKS YOU (PROBABLY) DON'T KNOW 🚀"
> Add a bio bar for authors at end of articles

- config/site_settings.ts
- pages/index.tsx
Some typos and language errors on the homepage
> Fix copy on homepage

- package-lock.json
- package.json
- pages/_app.tsx
Adds Fathom analytics for production
> Add Fathom Analytics

- components/ArticlePreview/ArticlePreview.tsx
- pages/articles/[slug].tsx
- Adds padding on articles for a small screen
- renames userId to user_id in bio footer
- Adds break point for author on small screens for article preview
> Fixes user_id typo in bio footer

- lib/blog.ts
- next.config.js
- package-lock.json
- package.json
- pages/articles/[slug].tsx
**feat:** use react markdown in place of inner html
Fixes conflicts
> Move to react markdown

- components/Nav/Nav.tsx
fixes #14 
Add the priority tag to the next image component in the Nav to prevent the logo from being lazy loaded. This will increase the speed that the logo will appear on the page.
> Add Priority to Logo In Navigation To Prevent Lazy Loading

- ISSUE_TEMPLATE.md
- Create template for issues, closes #52
None
None
> docs: Create issue template

- pages/articles/[slug].tsx
- Added Meta tags for dynamic SEO
- As there's another open issue for the OG image it's something not added here and should be considered for future improvements. 
- Close #74 
- None 
_( Welcome file extensions include gifs/png screenshots of your feature in action )_
- None
> Dynamic SEO tags

- pages/[username].tsx
- pages/articles/[slug].tsx
- I thought this was missing but turned out to be a bug and just needed to check the length of the array in the ternary to display the correct message. 
- Close #78 
- None
_( Welcome file extensions include gifs/png screenshots of your feature in action )_
- None
> Added length property 

- docker-compose.yml
- pages/articles/[slug].tsx
👉 _**Please remove the below and replace them with your own values, leaving the headers where they are.**_ 👈
- Add the Docker Compose file
- Close issue #77 
- @NiallJoeMaher helped offline
-  None
_( Welcome file extensions include gifs/png screenshots of your feature in action )_
- None
> Add Docker Compose File

- .env.development
- .gitignore
- README.md
- Adds a much more detailed README.md
- Adds a default `.env.development` file
- Updates `.gitignore` to ignore new `.env.development` file
Closes #73
> Adds more detailed README for installation

- .gitignore
- CONTRIBUTING.md
- e2e/example.spec.ts
- package-lock.json
- package.json
- playwright.config.ts
- This PR aims to bring Playwright as an e2e testing tool for the codu platform
A new `e2e` directory has been created to house all the e2e tests. 
To run test simple run `yarn test:e2e` or `npm run test:e2e` in your terminal after running `yarn dev`
Closes #86
> (feat): Setup playwright

- pages/articles/[slug].tsx
- Refers to domain in meta tags for OG images
> feat: Make articles reference domain for OG images

- docker-compose.yml
- package.json
Adds in `studio` script so that people can easily launch Prisma Studio.
Removes pgadmin comments from the `docker-compose` file. 
None
Closes #97.
> Add script to launch Prisma studio

- schema/post.ts
Updates the save schema to allow saving with an empty canonical URL which was causing a bug. 
Closes #100
> Allow save with empty canonical URL

- README.md
- INFO ABOUT YOUR PULL REQUEST GOES HERE (Please be as descriptive as possible) 🤜
- IF ANYTHING YOU'RE COMMITTING WOULD BREAK SOMETHING, INCLUDE HERE WHAT WOULD BREAK
- IF YOU HAVE NO BREAKING CHANGES, ENTER 'None'
_( Welcome file extensions include gifs/png screenshots of your feature in action )_
- IF YOU HAVE ANY SCREENSHOTS, INCLUDE THEM HERE.
- IF YOU HAVE NO SCREENSHOTS, ENTER 'None'
> Rename .env variable

- README.md
- next.config.js
- package-lock.json
- package.json
- prisma/seed.ts
This PR adds random seed users and data to the database so that people have some mock data to work with. 
None
> Add seed users with posts
